### ISSUE TITLE
Como usuario (paciente/cuidador) quiero registrarme (Sign Up) en la aplicación para obtener los beneficios que ofrece

### ISSUE THREAD

**Issue by rhjardine** [rhjardine/acompaname#1]
Requerimiento desarrollado durante el primer sprint. 

Estatus: Terminado

**Comment by rhjardine** [comment]
- [ ] El usuario puede imputar su correo, contraseña, nombres y apellidos.
- [ ] Al momento de efectuar registro el usuario tenga la opción de elegir entre cuidador o usuario.
- [ ] El usuario debe recibir una notificación de confirmación de su registro en la Web App a través del correo electronico u otro 
    medio o canal

**Comment by rhjardine** [comment]
Método POST /user 
{ email: usuario@gmail.com
 password: Pyt45877*
 name: Robert
last_name: Lopez }
RESPONSE
{ Id: email, name, last_name }

**Comment by Robiianna** [comment]
Cambiar archivo register html a jsx (front) @Robiianna
